(() => {
  "use strict";

  const SUPPORTED_LOCALES = {
    ENGLISH: "en",
    FRENCH_CANADA: "fr-CA",
  };

  const I18N = {
    en: {
      pageTitle: "Math Mage Defense",
      canvasAria: "Math Mage Defense game board",
      topBarAria: "Game controls and status",
      bottomBarAria: "Equation and cast results",
      appTitle: "Math Mage Defense",
      hudHp: "HP",
      hudWave: "Wave",
      hudStatus: "Status",
      hudLevelShort: "Lv",
      hudSpell: "Spell",
      profileLabel: "Profile",
      modeLabel: "Mode",
      speedLabel: "Speed",
      equationLabel: "Equation",
      lastCastLabel: "Last Cast",
      xpAria: "Experience progress",
      resetButton: "Reset",
      mapButton: "Map",
      pauseButton: "Pause",
      resumeButton: "Resume",
      clearButton: "Clear",
      castButton: "Cast",
      newButton: "New",
      modeAddSub: "Add/Subtract",
      modeMultiply: "Multiply",
      modeDivide: "Divide",
      statusRunning: "Running",
      statusPaused: "Paused",
      statusMap: "Map",
      statusVictory: "Victory",
      statusDefeat: "Defeat",
      equationDefault: "Select tokens: Number(s) -> Operator -> Number",
      lastCastDefault: "No casts yet.",
      spellUnlockTitle: "New Spell Unlocked",
      spellChainLightning: "Chain Lightning",
      spellMageTower: "Mage Tower",
      spellNew: "New Spell",
      spellNewDescription: "A new spell has been added to your grimoire.",
      debugMenuTitle: "Debug Menu",
      debugClose: "Close",
      debugCopy: "Testing tools for grown-up wizards.",
      debugUnlockLevels: "Unlock All Levels",
      debugGainXp: "Gain {xp} XP",
      debugResetProgress: "Reset Progression",
      spellStatusReady: "{name} ready",
      spellStatusLocked: "{name} L{level}",
      xpText: "{current} / {required} XP",
      chainLightningDescription: "Add/Sub: use a first number above 10, then press Enter or Cast Spell. Multiply: any result above 30 triggers it. Divide: use a divisor of 4 or more. Chain Lightning jumps across up to 3 enemies.",
      mageTowerDescription: "Solve a 3-number equation to awaken the tower. If the result matches an enemy target, the tower sends a burning wave across that lane for 5 damage to every enemy there.",
      levelUp: "Level Up!",
      levelNumberExclaim: "Level {level}!",
      profilePrompt: "Enter a profile name:",
      playerDefaultName: "Player {number}",
      profileNameEmpty: "Profile name cannot be empty.",
      profileCreated: "Profile {name} created.",
      profileLoaded: "Loaded profile {name}.",
      profileFallback: "Profile {number}",
      chainReadyHint: "Large spell ready. Press Enter or Cast Spell.",
      medusaPetrified: "Medusa petrified number {token}!",
      mageTowerEnterResult: "Mage Tower: enter a result first.",
      mageTowerIncorrect: "Mage Tower answer is incorrect.",
      mageTowerLaneDamage: "Mage Tower engulfs lane {lane} for {damage} damage.",
      enteringLevel: "Entering {level}.",
      worldMapHint: "World Map: tap the glowing island to begin",
      startWithLevel: "Start with {level}.",
      levelLocked: "Level locked: clear {level} first.",
      divisionByZero: "Division by zero is not allowed.",
      divisionWhole: "Division must produce a whole number.",
      numberPetrified: "Number {token} is petrified.",
      firstNumberLimit: "First number is limited to 2 digits.",
      secondNumberLimit: "Second number is limited to {digits} digits.",
      pickNumberFirst: "Pick a number first.",
      noEnemyMatches: "No enemy matches result {result}.",
      shieldRejects: "Shielded enemy rejects repeated equations. Try a different formula.",
      castChainLightning: "Cast! Chain Lightning arcs through {count} enemies.",
      castFireball: "Cast! Fireball launched at {enemy}.",
      castLightning: "Cast! Lightning strikes {enemy}.",
      hitLane: "Hit! {enemy} in lane {lane}.",
      eliminated: "Eliminated {enemy} (target {target}).",
      rerolled: "Hit! {enemy} rerolled {previous} to {next}.",
      levelComplete: "Level complete. Returning to World Map...",
      enemyBreach: "Enemy breach! Castle HP -{count}.",
      laneLabel: "Lane {lane}",
      tokenPanel: "Token Panel",
      touchTokenPanel: "Touch Token Panel",
      operatorMultiply: "Operator: x",
      operatorDivide: "Operator: ÷",
      operatorPlusMinus: "Operators: + and -",
      equationTitle: "Equation",
      inputHint: "Mouse/touch or numpad keys",
      clearHint: "Esc clears selection",
      worldMapTitle: "World Map",
      worldMapSubtitle: "Tap the glowing island to start. Higher islands are tougher and faster.",
      startHere: "Start here: {level}",
      startHereBadge: "START HERE",
      speedStat: "Speed {speed}x",
      stone: "STONE",
      slotA: "A",
      slotOp: "Op",
      slotB: "B",
      selectionHintMultiplyChain: "Number(s) -> x -> Number(s) (results above 30 chain)",
      selectionHintMultiply: "Number(s) -> x -> Number",
      selectionHintDivideChain: "Number(s) -> ÷ -> Number(s) (divisor 4+ chains, whole results only)",
      selectionHintDivide: "Number(s) -> ÷ -> Number (whole results only)",
      selectionHintLargeSpell: "Large spell: first number > 10, second number can use 2 digits, press Enter/Cast",
      selectionHintDefault: "Number(s) -> Operator -> Number",
      enemyHp: "{name} HP:{hp}",
      endVictory: "VICTORY",
      endDefeat: "DEFEAT",
      endResetHint: "Press Reset to play again",
      debugAllUnlocked: "Debug: all levels unlocked.",
      debugGainedXp: "Debug: gained {xp} XP.",
      debugResetDone: "Debug: progression reset for this profile.",
      operationHintMultiplyChain: "Select tokens: Number(s) -> (x) -> Number(s). Results above 30 trigger Chain Lightning.",
      operationHintMultiply: "Select tokens: Number(s) -> (x) -> Number",
      operationHintDivideChain: "Select tokens: Number(s) -> (÷) -> Number(s). Divisors of 4 or more trigger Chain Lightning.",
      operationHintDivide: "Select tokens: Number(s) -> (÷) -> Number",
      operationHintAddSubChain: "Select tokens: Number(s) -> (+/-) -> Number. First number above 10 enables Chain Lightning and Enter/Cast confirmation.",
      operationHintAddSub: "Select tokens: Number(s) -> (+/-) -> Number",
      enemy_goblin: "Plent",
      enemy_skeleton: "Skeleton",
      enemy_slime: "Slime",
      enemy_orc: "Skeleton Warrior",
      enemy_zombie: "Zombie Woman",
      enemy_carnivorousPlant: "Carnivorous Plant",
      enemy_minotaur: "Minotaur",
      enemy_medusa: "Medusa",
      level_misty_atoll: "Misty Atoll",
      level_sunspire_bay: "Sunspire Bay",
      level_patate_ratouille: "Patate Ratouille",
      level_emerald_marsh: "Emerald Marsh",
      level_crystal_isle: "Crystal Isle",
      level_bonecliff_isle: "Bonecliff Isle",
      level_stormbreak_reach: "Stormbreak Reach",
      level_ember_crown: "Ember Crown",
      level_darkspire_citadel: "DarkSpire Citadel",
    },
    "fr-CA": {
      pageTitle: "Math Mage Defense",
      canvasAria: "Plateau de jeu Math Mage Defense",
      topBarAria: "Commandes et état du jeu",
      bottomBarAria: "Équation et résultat du sort",
      appTitle: "Math Mage Defense",
      hudHp: "PV",
      hudWave: "Vague",
      hudStatus: "État",
      hudLevelShort: "Niv",
      hudSpell: "Sort",
      profileLabel: "Profil",
      modeLabel: "Mode",
      speedLabel: "Vitesse",
      equationLabel: "Équation",
      lastCastLabel: "Dernier sort",
      xpAria: "Progression d'expérience",
      resetButton: "Recommencer",
      mapButton: "Carte",
      pauseButton: "Pause",
      resumeButton: "Reprendre",
      clearButton: "Effacer",
      castButton: "Lancer",
      newButton: "Nouveau",
      modeAddSub: "Addition/Soustraction",
      modeMultiply: "Multiplication",
      modeDivide: "Division",
      statusRunning: "En cours",
      statusPaused: "En pause",
      statusMap: "Carte",
      statusVictory: "Victoire",
      statusDefeat: "Défaite",
      equationDefault: "Choisis des jetons : nombre(s) -> opérateur -> nombre",
      lastCastDefault: "Aucun sort lancé.",
      spellUnlockTitle: "Nouveau sort débloqué",
      spellChainLightning: "Éclair en chaîne",
      spellMageTower: "Tour du mage",
      spellNew: "Nouveau sort",
      spellNewDescription: "Un nouveau sort a été ajouté à ton grimoire.",
      debugMenuTitle: "Menu de débogage",
      debugClose: "Fermer",
      debugCopy: "Des outils de test pour les grands sorciers.",
      debugUnlockLevels: "Débloquer tous les niveaux",
      debugGainXp: "Gagner {xp} PX",
      debugResetProgress: "Réinitialiser la progression",
      spellStatusReady: "{name} prêt",
      spellStatusLocked: "{name} Niv {level}",
      xpText: "{current} / {required} PX",
      chainLightningDescription: "Addition/Soustraction : utilise un premier nombre plus grand que 10, puis appuie sur Entrée ou Lance le sort. Multiplication : tout résultat supérieur à 30 le déclenche. Division : utilise un diviseur de 4 ou plus. L'éclair en chaîne frappe jusqu'à 3 ennemis.",
      mageTowerDescription: "Résous une équation à 3 nombres pour réveiller la tour. Si le résultat correspond à la cible d'un ennemi, la tour envoie une vague brûlante dans cette voie et inflige 5 dégâts à tous les ennemis qui s'y trouvent.",
      levelUp: "Niveau supérieur!",
      levelNumberExclaim: "Niveau {level}!",
      profilePrompt: "Entre un nom de profil :",
      playerDefaultName: "Joueur {number}",
      profileNameEmpty: "Le nom du profil ne peut pas être vide.",
      profileCreated: "Profil {name} créé.",
      profileLoaded: "Profil {name} chargé.",
      profileFallback: "Profil {number}",
      chainReadyHint: "Grand sort prêt. Appuie sur Entrée ou Lance le sort.",
      medusaPetrified: "Méduse a pétrifié le jeton {token}!",
      mageTowerEnterResult: "Tour du mage : entre d'abord un résultat.",
      mageTowerIncorrect: "La réponse de la Tour du mage est incorrecte.",
      mageTowerLaneDamage: "La Tour du mage engloutit la voie {lane} et inflige {damage} dégâts.",
      enteringLevel: "Entrée dans {level}.",
      worldMapHint: "Carte du monde : touche l'île brillante pour commencer",
      startWithLevel: "Commence avec {level}.",
      levelLocked: "Niveau verrouillé : termine d'abord {level}.",
      divisionByZero: "La division par zéro est interdite.",
      divisionWhole: "La division doit donner un nombre entier.",
      tokenPetrified: "Le jeton {token} est pétrifié.",
      firstNumberLimit: "Le premier nombre est limité à 2 chiffres.",
      secondNumberLimit: "Le deuxième nombre est limité à {digits} chiffres.",
      pickNumberFirst: "Choisis d'abord un nombre.",
      noEnemyMatches: "Aucun ennemi ne correspond au résultat {result}.",
      shieldRejects: "L'ennemi protégé refuse les équations répétées. Essaie une autre formule.",
      castChainLightning: "Sort lancé! L'éclair en chaîne frappe {count} ennemis.",
      castFireball: "Sort lancé! Une boule de feu vise {enemy}.",
      castLightning: "Sort lancé! La foudre frappe {enemy}.",
      hitLane: "Touché! {enemy} dans la voie {lane}.",
      eliminated: "{enemy} éliminé (cible {target}).",
      rerolled: "Touché! {enemy} change sa cible de {previous} à {next}.",
      levelComplete: "Niveau terminé. Retour à la carte du monde...",
      enemyBreach: "Brèche ennemie! PV du château -{count}.",
      laneLabel: "Voie {lane}",
      tokenPanel: "Panneau des jetons",
      touchTokenPanel: "Panneau tactile des jetons",
      operatorMultiply: "Opérateur : x",
      operatorDivide: "Opérateur : ÷",
      operatorPlusMinus: "Opérateurs : + et -",
      equationTitle: "Équation",
      inputHint: "Souris/tactile ou touches du pavé numérique",
      clearHint: "Échap efface la sélection",
      worldMapTitle: "Carte du monde",
      worldMapSubtitle: "Touche l'île brillante pour commencer. Les îles plus hautes sont plus rapides et plus difficiles.",
      startHere: "Commence ici : {level}",
      startHereBadge: "COMMENCE ICI",
      speedStat: "Vitesse {speed}x",
      stone: "PIERRE",
      slotA: "A",
      slotOp: "Op",
      slotB: "B",
      selectionHintMultiplyChain: "Nombre(s) -> x -> Nombre(s) (résultats au-dessus de 30 en chaîne)",
      selectionHintMultiply: "Nombre(s) -> x -> Nombre",
      selectionHintDivideChain: "Nombre(s) -> ÷ -> Nombre(s) (diviseur 4+ en chaîne, résultats entiers seulement)",
      selectionHintDivide: "Nombre(s) -> ÷ -> Nombre (résultats entiers seulement)",
      selectionHintLargeSpell: "Grand sort : premier nombre > 10, le deuxième peut avoir 2 chiffres, puis Entrée/Lancer",
      selectionHintDefault: "Nombre(s) -> Opérateur -> Nombre",
      enemyHp: "{name} PV:{hp}",
      endVictory: "VICTOIRE",
      endDefeat: "DÉFAITE",
      endResetHint: "Appuie sur Recommencer pour rejouer",
      debugAllUnlocked: "Débogage : tous les niveaux sont débloqués.",
      debugGainedXp: "Débogage : {xp} PX gagnés.",
      debugResetDone: "Débogage : progression réinitialisée pour ce profil.",
      operationHintMultiplyChain: "Choisis des jetons : nombre(s) -> (x) -> nombre(s). Les résultats au-dessus de 30 déclenchent l'éclair en chaîne.",
      operationHintMultiply: "Choisis des jetons : nombre(s) -> (x) -> nombre",
      operationHintDivideChain: "Choisis des jetons : nombre(s) -> (÷) -> nombre(s). Les diviseurs de 4 ou plus déclenchent l'éclair en chaîne.",
      operationHintDivide: "Choisis des jetons : nombre(s) -> (÷) -> nombre",
      operationHintAddSubChain: "Choisis des jetons : nombre(s) -> (+/-) -> nombre. Un premier nombre supérieur à 10 active l'éclair en chaîne et la confirmation Entrée/Lancer.",
      operationHintAddSub: "Choisis des jetons : nombre(s) -> (+/-) -> nombre",
      enemy_goblin: "Plent",
      enemy_skeleton: "Squelette",
      enemy_slime: "Gelée",
      enemy_orc: "Guerrier squelette",
      enemy_zombie: "Zombie",
      enemy_carnivorousPlant: "Plante carnivore",
      enemy_minotaur: "Minotaure",
      enemy_medusa: "Méduse",
      level_misty_atoll: "Atoll brumeux",
      level_sunspire_bay: "Baie de Solespire",
      level_patate_ratouille: "Patate Ratatouille",
      level_emerald_marsh: "Marais d'émeraude",
      level_crystal_isle: "Île de cristal",
      level_bonecliff_isle: "Île des falaises d'os",
      level_stormbreak_reach: "Cap de la tempête",
      level_ember_crown: "Couronne des braises",
      level_darkspire_citadel: "Citadelle de Flèchenoire",
    },
  };

  const ENEMY_NAME_KEYS = {
    goblin: "enemy_goblin",
    skeleton: "enemy_skeleton",
    slime: "enemy_slime",
    orc: "enemy_orc",
    zombie: "enemy_zombie",
    carnivorousPlant: "enemy_carnivorousPlant",
    minotaur: "enemy_minotaur",
    medusa: "enemy_medusa",
  };

  const LEVEL_NAME_KEYS = {
    "misty-atoll": "level_misty_atoll",
    "sunspire-bay": "level_sunspire_bay",
    "patate-ratouille": "level_patate_ratouille",
    "emerald-marsh": "level_emerald_marsh",
    "crystal-isle": "level_crystal_isle",
    "bonecliff-isle": "level_bonecliff_isle",
    "stormbreak-reach": "level_stormbreak_reach",
    "ember-crown": "level_ember_crown",
    "darkspire-citadel": "level_darkspire_citadel",
  };

  function detectLocale() {
    const browserLanguages = Array.isArray(window.navigator.languages)
      ? window.navigator.languages
      : [];
    const primaryLanguage = browserLanguages[0] || window.navigator.language || "en";
    const normalizedPrimaryLanguage = String(primaryLanguage).toLowerCase();

    return normalizedPrimaryLanguage.startsWith("fr")
      ? SUPPORTED_LOCALES.FRENCH_CANADA
      : SUPPORTED_LOCALES.ENGLISH;
  }

  function createLocalization() {
    const activeLocale = detectLocale();

    function t(key, values = {}) {
      const template = I18N[activeLocale]?.[key] ?? I18N.en[key] ?? key;
      return template.replace(/\{(\w+)\}/g, (matchText, valueKey) => {
        if (!Object.prototype.hasOwnProperty.call(values, valueKey)) {
          return matchText;
        }
        return String(values[valueKey]);
      });
    }

    function getLevelDisplayName(level) {
      if (!level) {
        return "";
      }
      const levelKey = LEVEL_NAME_KEYS[level.key];
      return levelKey ? t(levelKey) : level.name;
    }

    function getEnemyDisplayName(enemyType, fallbackName = enemyType) {
      const enemyKey = ENEMY_NAME_KEYS[enemyType];
      return enemyKey ? t(enemyKey) : fallbackName;
    }

    return {
      activeLocale,
      t,
      getLevelDisplayName,
      getEnemyDisplayName,
    };
  }

  window.MathMageLocalization = {
    createLocalization,
  };
})();